"""Add interaction foreign key

Revision ID: 1c1f4690b870
Revises: 4e0038ef37f1
Create Date: 2024-07-03 12:26:58.370905

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1c1f4690b870'
down_revision = '4e0038ef37f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'interactionsummary', 'domainsummary', ['ted_id2'], ['ted_id'])
    op.create_foreign_key(None, 'interactionsummary', 'domainsummary', ['ted_id1'], ['ted_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interactionsummary', type_='foreignkey')
    op.drop_constraint(None, 'interactionsummary', type_='foreignkey')
    # ### end Alembic commands ###
