"""add ChainParse model

Revision ID: 1e6318b08856
Revises: 85154885ffac
Create Date: 2024-07-31 11:56:47.235175

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1e6318b08856'
down_revision = '85154885ffac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chainparse',
    sa.Column('af_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uniprot_acc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('md5_chain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nres_chain', sa.Integer(), nullable=False),
    sa.Column('num_domains', sa.Integer(), nullable=False),
    sa.Column('chopping', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chainparse_md5_chain'), 'chainparse', ['md5_chain'], unique=False)
    op.create_index(op.f('ix_chainparse_method'), 'chainparse', ['method'], unique=False)
    op.create_index(op.f('ix_chainparse_uniprot_acc'), 'chainparse', ['uniprot_acc'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chainparse_uniprot_acc'), table_name='chainparse')
    op.drop_index(op.f('ix_chainparse_method'), table_name='chainparse')
    op.drop_index(op.f('ix_chainparse_md5_chain'), table_name='chainparse')
    op.drop_table('chainparse')
    # ### end Alembic commands ###
