"""Add interaction model

Revision ID: 4e0038ef37f1
Revises: 67fd00f08e4a
Create Date: 2024-07-03 12:17:21.479842

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4e0038ef37f1'
down_revision = '67fd00f08e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactionsummary',
    sa.Column('af_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ted_id1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ted_id2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pae_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('af_id')
    )
    op.create_index(op.f('ix_interactionsummary_ted_id1'), 'interactionsummary', ['ted_id1'], unique=False)
    op.create_index(op.f('ix_interactionsummary_ted_id2'), 'interactionsummary', ['ted_id2'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interactionsummary_ted_id2'), table_name='interactionsummary')
    op.drop_index(op.f('ix_interactionsummary_ted_id1'), table_name='interactionsummary')
    op.drop_table('interactionsummary')
    # ### end Alembic commands ###
