name: Deploy to Production (CS)

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    environment: "CS Production"
    runs-on:
      - self-hosted
      - production
      - cs
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN }}
      STACK_NAME: ${{ secrets.STACK_NAME }}
      BACKEND_CORS_ORIGIN: ${{ secrets.BACKEND_CORS_ORIGIN }}
      DOCKER_IMAGE_BACKEND: ${{ secrets.DOCKER_IMAGE_BACKEND }}
      DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKER_IMAGE_FRONTEND }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      FIRST_SUPERUSER: ${{ secrets.FIRST_SUPERUSER }}
      FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      EMAILS_FROM_EMAIL: ${{ secrets.EMAILS_FROM_EMAIL }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      POSTGRES_SERVER: ${{ secrets.POSTGRES_SERVER }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cp .env.cs .env
      - run: docker compose -f docker-compose.cs.yml build
      - run: docker compose -f docker-compose.cs.yml up -d
